providers:
  - id: http
    config:
      url: 'http://localhost:8000/chat'
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        sessionid: 'test'
        message: '{{message}}'
      transformResponse: 'json.response'

prompts:
  - "{{message}}"

tests:
  - provider: http
    vars:
      message: "tell me who is the president of india"
    assert:
      - type: llm-rubric
        value: "The response should mention the current president of India"
  - provider: http
    vars:
      message: "what is his age?"
    assert:
      - type: llm-rubric
        value: "The response should mention the president's age"